"""The generated torrc must actually parse, or every lane silently dies.

    python tools/verify/verify_torrc.py

Why this exists. `_lane_config` grew four directives and changed one
(`SocksPort ... IsolateSOCKSAuth KeepAliveIsolateSOCKSAuth`, `SocksTimeout`,
`CircuitStreamTimeout`, `KeepalivePeriod`, `ConnectionPadding`, and a new
`Log` domain). Every offline suite passed, and the whole audit reported clean --
because none of them ever asks Tor whether the file it is handed is legal.

It was not. `Log [circ,stream]notice` names a logging domain that does not
exist ("No such logging domain as stream"), Tor refuses the config, exits
before writing a single line, and the lane never listens. `tor.log` was 0
bytes and the failure surfaced only as "the lane never listened" four minutes
later.

The domains Tor actually accepts are general, circ, or, edge, dir, entry and
bug -- stream-level events are under `edge`. `edge` is what this pins.

Skipped, not failed, when tor is not present: this is a config check, and a
machine without the bundle cannot run it. The audit's other suites still cover
everything else.
"""
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from lingling import data_dir  # noqa: E402
from lingling.lanes import Lane, TorManager  # noqa: E402

FAILS = []


def check(name, ok, detail=""):
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}"
          + (f" -- {detail}" if detail else ""))
    if not ok:
        FAILS.append(name)


def manager():
    """A TorManager shell: only what `_lane_config` reaches for."""
    m = TorManager.__new__(TorManager)
    m.tools_dir = data_dir() / "tools"
    m.lanes_dir = data_dir() / "lanes"
    m.tor_exe_override = ""
    m._tor_executable = None
    return m


def tor_binary():
    m = manager()
    for p in m.tools_dir.rglob("tor.exe" if sys.platform == "win32" else "tor"):
        return p
    return None


def main():
    tor = tor_binary()
    if tor is None:
        print("  [SKIP] tor is not installed -- cannot validate the torrc")
        return 0

    print("=== the generated torrc parses ===")
    m = manager()
    lane = Lane(index=1, socks_port=52001, control_port=52301,
                exit_country="de", data_dir=data_dir() / "lanes" / "tor-1")
    cfg = m._lane_config(lane)
    lines = ["# generated by verify_torrc"] + [f"{k} {v}" for k, v in cfg.items()]

    tmp = pathlib.Path(tempfile.gettempdir()) / "lingling-torrc-check.torrc"
    tmp.write_text("\n".join(lines), encoding="utf-8")
    try:
        out = subprocess.run(
            [str(tor), "--verify-config", "-f", str(tmp)],
            capture_output=True, text=True, timeout=60).stdout
    except Exception as exc:  # noqa: BLE001
        check("tor --verify-config runs", False, f"{type(exc).__name__}")
        return 1

    bad = [ln for ln in out.splitlines()
           if "[warn]" in ln or "[err]" in ln]
    check("tor accepts the whole file", not bad,
          bad[0] if bad else "Configuration was valid")

    print("\n=== the directives this pins ===")
    socks = cfg.get("SocksPort", "")
    check("SocksPort isolates by credential",
          "IsolateSOCKSAuth" in socks and "KeepAliveIsolateSOCKSAuth" in socks,
          socks)
    check("the log domain is a real one",
          cfg.get("Log", "").startswith("[circ,edge]"), cfg.get("Log", ""))
    check("CircuitBuildTimeout is gone (it is a no-op)",
          "CircuitBuildTimeout" not in cfg)
    check("conflux is off by default (it was cutting streams)",
          cfg.get("ConfluxEnabled") == "0", f"ConfluxEnabled={cfg.get('ConfluxEnabled')}")

    print("\n" + "=" * 46)
    if FAILS:
        print(f"FAILURES: {len(FAILS)}")
        for f in FAILS:
            print("  - " + f)
        return 1
    print("TORRC: VALID")
    return 0


if __name__ == "__main__":
    sys.exit(main())
